using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using FMODUnity;
using FMOD.Studio;
using System;
using System.Text;
using System.IO;
using System.Runtime.InteropServices;
using Newtonsoft.Json;
using Cysharp.Threading.Tasks;

public class NoteGeneratorByEditor : StreamingAssetPather
{
    public static NoteGeneratorByEditor Instance { get; private set; }
    [SerializeField]
    private int _level;
    [SerializeField]
    private NoteGeneratorData _generatorData;

    [Header("------------------ Text/Obj Setting -----------------")]
    [SerializeField]
    private UnityEngine.UI.Text _villageText;
    [SerializeField]
    private UnityEngine.UI.Text _levelText;
    [SerializeField]
    private UnityEngine.UI.Text _bpmText;
    [SerializeField]
    private UnityEngine.UI.Text _totalMarkerCntText;
    [SerializeField]
    private GameObject _noteGeneratorUnitParent;
    [SerializeField]
    private Color32[] _colors; //0: white, 1: Red

    [Header("------------------ Btn Setting -----------------")]
    [SerializeField]
    private Button _setInfoBtn;
    [SerializeField]
    private Button _generateBtn;
    [SerializeField]
    private Button _prevBtn;
    [SerializeField]
    private Button _nextBtn;
    [SerializeField]
    private Button _InitZeroBtn;

    [Header("------------------ FileIO Field -----------------")]
    private static StreamWriter _sw;
    private StageInfo _stageInfo = null;
    private string _stageJson = null;
    public List<NoteGeneratorUnit> noteGeneratorUnits { get; set; }
    private int _usedBeatCnt;
    /// <summary>
    /// 총 사용된 비트 수(**기믹 노트 개수 아님)
    /// </summary>
    public int usedBeatCnt
    {
        get { return _usedBeatCnt; }
        set
        {
            _usedBeatCnt = value;
            _totalMarkerCntText.text = _usedBeatCnt.ToString() + "/" + _totalBeatCnt.ToString();
            _totalMarkerCntText.color = _colors[usedBeatCnt > _totalBeatCnt ? 1 : 0];
        }
    }
    /// <summary>
    /// 전체 사용가능 비트 수
    /// </summary>
    private int _totalBeatCnt = 0;
    /// <summary>
    /// 전체 사용된 기믹 노트 개수(기믹마다 점유 비트가 다르기때문에 따로 셈)
    /// </summary>
    private int _totalMarkerCnt = 0;
    private List<int> _beatCnts; //각 노트 별 점유하는 박자 수 저장

    #region Unity Life Cycle
    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }

#if UNITY_EDITOR
        Application.runInBackground = true;
#endif
    }

    private async void Start()
    {
        _setInfoBtn?.onClick.AddListener(OnClickSetInfoBtn);
        _generateBtn?.onClick.AddListener(OnClickGenerateBtn);
        _prevBtn?.onClick.AddListener(OnClickPrevBtn);
        _nextBtn?.onClick.AddListener(OnClickNextBtn);
        _InitZeroBtn?.onClick.AddListener(OnClickInitZeroBtn);

        LoadNoteData(_level);
    }
    #endregion

    #region UI Action
    private void OnClickInitZeroBtn()
    {
        usedBeatCnt = 0;
        for (int i = 0; i < noteGeneratorUnits.Count; i++)
        {
            noteGeneratorUnits[i].gimmickCnt = 0;
        }
    }

    private void OnClickSetInfoBtn()
    {
        usedBeatCnt = 0;
        _totalMarkerCnt = 0;
        for (int i = 0; i < noteGeneratorUnits.Count; i++)
        {
            _totalMarkerCnt += noteGeneratorUnits[i].gimmickCnt;
            usedBeatCnt += (noteGeneratorUnits[i].info.totalBeatCnt * noteGeneratorUnits[i].gimmickCnt);
        }
    }

    private void OnClickGenerateBtn()
    {
        if (usedBeatCnt > _totalBeatCnt)
        {
            Debug.Log($"사용 가능 비트 수가 전체 비트 수 보다 큽니다. 노트 생성 불가능.");
            return;
        }

        _stageInfo.isAutoGenerated = true;

        // 전체 노트 수 == 사용된 기믹 노트 수 + 공백 수(1개를 1비트로 환산)
        _beatCnts = new List<int>();
        _stageInfo.noteDatas.Clear();
        _stageInfo.noteDatas = new List<NoteInfo>();
        _stageInfo.noteCnt = 0;

        // 기믹 노트 추가
        for (int i = 0; i < noteGeneratorUnits.Count; i++)
        {
            SetNoteInfo(noteGeneratorUnits[i], ref _beatCnts);
        }

        // 공백 노트 추가
        int emptyBeats = _totalBeatCnt - usedBeatCnt;
        for (int k = 0; k < emptyBeats; k++)
        {
            NoteInfo info = new NoteInfo()
            {
                noteType = Define.NoteType.NotAvailable, // 공백
            };
            _stageInfo.noteDatas.Add(info);
            _beatCnts.Add(1); // 공백은 1박자
        }

        // _stageInfo.noteDatas의 순서를 랜덤하게 섞음 (Fisher-Yates Algorithm)
        int count = _stageInfo.noteDatas.Count;
        for (int q = count - 1; q > 0; q--)
        {
            int j = UnityEngine.Random.Range(0, q + 1);
            (_stageInfo.noteDatas[q], _stageInfo.noteDatas[j]) = (_stageInfo.noteDatas[j], _stageInfo.noteDatas[q]);
            (_beatCnts[q], _beatCnts[j]) = (_beatCnts[j], _beatCnts[q]);
        }

        // 새로 생성된 순서에 맞게 박자 position 할당, 공백은 다음 박자로 처리
        int curBeatMarker = InGameKey.maxNoteRoadCnt;
        for (int t = 0; t < count; t++)
        {
            _stageInfo.noteDatas[t].position = (int)(_stageInfo.distancePerMarker * curBeatMarker);
            curBeatMarker += _beatCnts[t];
        }

        // 노트 생성
        WriteJson(_level);
    }

    private void OnClickPrevBtn()
    {
        if (_level <= 1)
        {
            return;
        }

        LoadNoteData(SceneSwitcher.IsBonusStage(--_level) ? --_level : _level);
    }

    private void OnClickNextBtn()
    {
        if (_level >= 440)
        {
            return;
        }

        LoadNoteData(SceneSwitcher.IsBonusStage(++_level)? ++_level : _level);
    }
    #endregion

    #region File I/O
    public async void LoadNoteData(int level)
    {
        if (level > 440)
        {
            Debug.Log($"노트 생성 가능 최대 레벨 달성. 종료합니다.");
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#endif
            return;
        }

        string filePath;
        Define.TownList town = SceneSwitcher.GetTownList(level);
        _villageText.text = town.ToString();
        _levelText.text = _level.ToString();
        _stageInfo = new StageInfo();
        _usedBeatCnt = 0;

        filePath = GetFilePathCommon(town, level);
        if (File.Exists(filePath))
        {
            _stageJson = File.ReadAllText(filePath);
            _stageInfo = JsonUtility.FromJson<StageInfo>(_stageJson);
            _totalBeatCnt = _stageInfo.totalBeatMarkerCnt - InGameKey.maxNoteRoadCnt - InGameKey.lastNoteSpaceBeatCnt;
            _bpmText.text = "BPM: " + _stageInfo.bpm.ToString();

            InitGeneratorUnit();
            //자동 생성된 것만 카운트 로직 들어감. 자동 생성이 아닐 경우 무조건 덮어씀
            if (!_stageInfo.isAutoGenerated)
            {
                //자동생성 X, 덮어씀
                usedBeatCnt = 0;
            }
            else
            {
                SetData();
            }
        }
        else
        {
            //TODO: 파일 생성 및 기본 노트 데이터 생성
        }
    }

    private void WriteJson(int level)
    {
        Define.TownList town = SceneSwitcher.GetTownList(level);
        string filePath = GetFilePathCommon(town, level);

        // 경로가 없으면 폴더 생성
        if (!Directory.Exists(Path.GetDirectoryName(filePath)))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(filePath));
        }

        _sw = new StreamWriter(filePath);
        _sw.WriteLine(JsonHelper.ObjectToJson(_stageInfo));
        _sw.Flush();
        _sw.Close();
        Debug.Log($"{town}-{level}, {filePath} =>  총 마커수: {_stageInfo.totalBeatMarkerCnt}, NoteData 자동 생성 및 저장 완료 Json");
    }
    #endregion

    #region Note Generator
    private void SetData()
    {
        if (_stageInfo == null)
        {
            Debug.Log("_stageInfo NULL");
            return;
        }

        for (int i = 0; i < _stageInfo.noteDatas.Count; i++)
        {
            if (_stageInfo.noteDatas[i].gimmickKey < 0)
            {
                //Debug.Log($"{_stageInfo.noteDatas[i].gimmickKey}: noteData gimmickKey 음수");
                continue;
            }
            UpdateUnitInfo(_stageInfo.noteDatas[i].gimmickKey);
        }
    }

    public void UpdateUnitInfo(int gimmickKey)
    {
        noteGeneratorUnits[gimmickKey].gimmickCnt++;
        usedBeatCnt += noteGeneratorUnits[gimmickKey].info.totalBeatCnt;
    }

    private void InitGeneratorUnit()
    {
        BaseObjectPool.Instance.ClearPool(_noteGeneratorUnitParent);
        noteGeneratorUnits = new List<NoteGeneratorUnit>(_generatorData.unitInfo.Length);
        for (int i = 0; i < _generatorData.unitInfo.Length; i++)
        {
            GameObject unit = BaseObjectPool.Instance.Spawn(PoolingKeys.NoteGenerator, _noteGeneratorUnitParent);
            unit.GetComponent<NoteGeneratorUnit>().InitInfo(_generatorData.unitInfo[i], _level >= _generatorData.unitInfo[i].appearLevel);
            noteGeneratorUnits.Add(unit.GetComponent<NoteGeneratorUnit>());
        }
    }

    private void SetNoteInfo(NoteGeneratorUnit unit, ref List<int> beatCnts)
    {
        if (unit.gimmickCnt < 1)
        {
            //기믹 개수가 0이라서 넣을 필요 없음
            return;
        }

        for (int i = 0; i < unit.gimmickCnt; i++)
        {
            // 공통 정보 세팅
            NoteInfo info = new NoteInfo()
            {
                noteType = Define.NoteType.N_,
                noteActionType = unit.info.actionType,
                noteGimmickType = unit.info.gimmickType,
                noteDuplicateCnt = unit.info.isDouble ? 2 : 1,
                rspTypes = new Define.RSPType[InGameKey.maxNoteDuplicateCnt],
                logicTypes = new Define.LogicType[InGameKey.maxNoteDuplicateCnt],
                inputTypes = new Define.InputType[InGameKey.maxNoteDuplicateCnt],
                inputIndexes = new int[InGameKey.maxNoteDuplicateCnt],
                tutorialType = Define.InGameTutorialType.None,
                gimmickParameters = new int[InGameKey.maxNoteGimmickParameterCnt],
                gimmickKey = unit.info.gimmickKey,
            };

            // Note Info Setting Logic
            string duplicateType = string.Empty;
            int ruleIndex = UnityEngine.Random.Range(0, GetMaxRuleIndex(_level));
            switch (info.noteGimmickType)
            {
                case Define.NoteTypeN.N_HIT:
                    info.gimmickParameters = new int[2] { unit.info.totalBeatCnt, HitCntByBPM(unit.info.totalBeatCnt, _stageInfo.bpm) }; //박자, 횟수
                    _stageInfo.noteCnt += info.gimmickParameters[1];
                    break;
                case Define.NoteTypeN.N_SCT:
                case Define.NoteTypeN.N_SCF:
                case Define.NoteTypeN.N_SCH:
                    info.noteActionType = Define.NoteTypeA.A_CLK; //무조건 클릭
                    _stageInfo.noteCnt++;
                    break;
                case Define.NoteTypeN.N_BRD:
                    info.gimmickParameters[0] = unit.info.totalBeatCnt; //박자
                    info.noteDuplicateCnt = 1;
                    info.inputTypes[0] = Define.InputType.RSP;
                    info.rspTypes[0] = GetRandomRSPType();
                    info.inputIndexes[0] = (int)info.rspTypes[0];
                    _stageInfo.noteCnt++;
                    break;
                case Define.NoteTypeN.N_SHY:
                    if (info.noteActionType == Define.NoteTypeA.A_HLD)
                    {
                        info.noteActionType = Define.NoteTypeA.A_CLK;
                    }
                    break;
                case Define.NoteTypeN.N_PAL:
                    info.noteDuplicateCnt = 1;
                    info.inputTypes[0] = Define.InputType.RSP;
                    info.inputTypes[1] = Define.InputType.RSP;
                    info.inputIndexes[0] = (int)GetRandomRSPType();
                    info.rspTypes = GetPalRSPTypes((Define.RSPType)info.inputIndexes[0]);
                    _stageInfo.noteCnt++;
                    break;
                case Define.NoteTypeN.N_PCK:
                    info.noteDuplicateCnt = 1;
                    info.gimmickParameters[0] = unit.info.totalBeatCnt; //박자
                    info.inputTypes[0] = Define.InputType.RSP;
                    info.inputTypes[1] = Define.InputType.RSP;
                    info.rspTypes[0] = GetRandomRSPType();
                    info.rspTypes[1] = GetRandomRSPType();
                    info.logicTypes[0] = (Define.LogicType)GetRandomRSPType();
                    info.logicTypes[1] = (Define.LogicType)GetRandomRSPType();
                    info.inputIndexes[0] = (int)Define.RSPType.Rock;
                    info.inputIndexes[1] = (int)Define.RSPType.Rock;
                    _stageInfo.noteCnt += InGameKey.notePCKHitCnt;
                    break;
                default:
                    info.logicTypes[0] = (Define.LogicType)ruleIndex;
                    if (unit.info.isDouble)
                    {
                        info.noteDuplicateCnt = 2;
                        info.inputTypes[0] = Define.InputType.RSP;
                        info.inputTypes[1] = Define.InputType.RSP;
                        info.rspTypes[0] = GetRandomRSPType();
                        info.rspTypes[1] = unit.info.isSameDouble ? info.rspTypes[0] : GetDifferentRandomRSPType(info.rspTypes[0]);
                        info.inputIndexes[0] = JsonNoteLoader.SetCorrectIndex(ruleIndex, (int)info.rspTypes[0]);
                        info.inputIndexes[1] = JsonNoteLoader.SetCorrectIndex(ruleIndex, (int)info.rspTypes[1]);
                        _stageInfo.noteCnt++;
                    }
                    else
                    {
                        info.noteDuplicateCnt = 1;
                        info.inputTypes[0] = Define.InputType.RSP;
                        info.rspTypes[0] = GetRandomRSPType();
                        info.inputIndexes[0] = JsonNoteLoader.SetCorrectIndex(ruleIndex, (int)info.rspTypes[0]);
                    }
                    if (info.noteActionType == Define.NoteTypeA.A_HLD)
                    {
                        info.gimmickParameters[0] = unit.info.totalBeatCnt; //박자
                        _stageInfo.noteCnt++; // 홀드노트는 판정이 2개 이기 때문에(시작점, 유지기간), noteCnt가 2개임
                    }
                    _stageInfo.noteCnt++;
                    break;
            }

            _stageInfo.noteDatas.Add(info); 
            beatCnts.Add(unit.info.totalBeatCnt);
        }
    }

    private int HitCntByBPM(int beatCnt, float bpm)
    {
        int singleBeatHitCnt = 0;

        if(bpm <= 45)
        {
            singleBeatHitCnt = 5;
        }
        else if(bpm <= 90)
        {
            singleBeatHitCnt = 4;
        }
        else if(bpm <= 135)
        {
            singleBeatHitCnt = 3;
        }
        else
        {
            singleBeatHitCnt = 2;
        }

        return beatCnt * singleBeatHitCnt;
    }

    private Define.RSPType GetRandomRSPType()
    {
        return (Define.RSPType)UnityEngine.Random.Range((int)Define.RSPType.Rock, (int)Define.RSPType.Paper + 1);
    }

    private Define.RSPType GetDifferentRandomRSPType(Define.RSPType selectedType)
    {
        // RSPType의 모든 값을 가져옴
        Define.RSPType[] allTypes = (Define.RSPType[])Enum.GetValues(typeof(Define.RSPType));
        int count = allTypes.Length - 1; // None을 제외하기 위해 -1
        Define.RSPType[] differentTypes = new Define.RSPType[count - 1]; // selectedType을 제외하기 위해 -1

        int index = 0;
        for (int i = 0; i < allTypes.Length; i++)
        {
            if (allTypes[i] != Define.RSPType.None && allTypes[i] != selectedType)
            {
                differentTypes[index] = allTypes[i];
                index++;
            }
        }

        // 리스트에서 랜덤한 값을 선택하여 반환
        int randomIndex = UnityEngine.Random.Range(0, differentTypes.Length);
        return differentTypes[randomIndex];
    }

    private int GetMaxRuleIndex(int curLevel)
    {
        if(curLevel >= (int)Define.NoteLogicAppearLevel.Lose)
        {
            return (int)Define.LogicType.Lose + 1;
        }else if(curLevel >= (int)Define.NoteLogicAppearLevel.Draw)
        {
            return (int)Define.LogicType.Draw + 1;
        }
        else
        {
            return (int)Define.LogicType.Win + 1;
        }
    }

    private Define.RSPType[] GetPalRSPTypes(Define.RSPType inputType)
    {
        Define.RSPType[] types = new Define.RSPType[2];

        switch (inputType)
        {
            default:
            case Define.RSPType.Rock:
                types[0] = Define.RSPType.Scissor;
                types[1] = Define.RSPType.Paper;
                break;
            case Define.RSPType.Scissor:
                types[0] = Define.RSPType.Rock;
                types[1] = Define.RSPType.Paper;
                break;
            case Define.RSPType.Paper:
                types[0] = Define.RSPType.Rock;
                types[1] = Define.RSPType.Scissor;
                break;
        }

        return types;
    }
    #endregion
}